<?php
global $wp_version , $submenu ;
$fxd_label = "fxd_pwpa";
	$fxdOptionsDashboard[] = array(
		  "id" => $fxd_label."_show_welcome",
		  "name" => "Add your own Welcome Panel?",
          "std" => "1");
	$fxdOptionsDashboard[] = array(
		 "name" => "Visible To",
         "description" => "This means the welcome panel will appear for users with roles higher or equal to the one chosen.",
         "id" => $fxd_label."_welcome_visible_to",
         "type" => "select",
         "options"=>fxd_roles_dropdown(),
         "std" => 'editor');
	$fxdOptionsDashboard[] = array(
		"name" => "Title",
        "description" => "The title of your dashboard panel.",
        "id" => $fxd_label."_welcome_title",
        "type" => "text",
        "std" => 'Welcome To Your New Website');
	$fxdOptionsDashboard[] = array(
		"name" => "Description",
		"description" => "The title of your dashboard panel.",
        "type" => "subtitle",
        "id" => $fxd_label."_welcome_text",
        "type" => "textarea",
        "std" => '');
	$fxdOptionsDashboard[] = array(
		"name" => "Second Panel Settings",
		"type" => "subtitle" );
	$fxdOptionsDashboard[] = array(
		 "name" => "Visible To",
         "description" => "This means the welcome panel will appear for users with roles higher or equal to the one chosen.",
         "id" => $fxd_label."_welcome_visible_to1",
         "type" => "select",
         "options"=>fxd_roles_dropdown(),
         "std" => 'editor');
	$fxdOptionsDashboard[] = array(
		"name" => "Title",
        "description" => "The title of your dashboard panel.",
        "id" => $fxd_label."_welcome_title1",
        "type" => "text",
        "std" => 'Your Custom Widget Title');
	$fxdOptionsDashboard[] = array(
		"name" => "Description",
		"description" => "The title of your dashboard panel.",
        "type" => "subtitle",
        "id" => $fxd_label."_welcome_text1",
        "type" => "textarea",
        "std" => '');				
$fxdOptionsDashboard = array_merge($fxdOptionsDashboard);
?>