<?php
global $wp_version , $submenu ;
$fxd_label = "fxd_pwpa";
	$fxdOptionsPermission[] = array(
		  "id" => $fxd_label."_show_welcome",
		  "name" => "Add your own Welcome Panel?",
          "description" => "This will appear on the dashboard. We recommend providing your contact details and links to the help files you have made for your client.",
          "options" => array("1", "0"),
          "std" => "1");
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_enable_login_redirect",
		"name" => "Enable Login URL Redirect",
		"description" => "Clients can go to /login as well as /wp-login.php only when permalinks are enabled",
		"type" => "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 1);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_dashboard_remove_nag_update",
		"name" => "Hide Nag Update",
		"description" => "This will hide the Nag Update for out of date versions of WordPress",
		"type" => "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 1);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_dashboard_remove_help_box",
		"name" => "Hide Help Box",
		"description" => "This will hide the Help Box dropdown",
		"type" => "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);	
	$fxdOptionsPermission[] = array(
		"id"  => $fxd_label."_dashboard_remove_screen_options",
		"name" => "Hide Screen Options",
		"description" => "This will hide the Screen Options dropdown",
		"type" => "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_hide_quickdraft",
		"name" => "Hide Quick Draft ",
		"description" => "Hide Quick Draft Widget from Dashboard",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_wp_news",
		"name" => "Hide Wordpress News",
		"description" => "Hides the Wordpress News widget form dashboard",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_meta_box_gan",
		"name" => "Hide Meta Box ",
		"description" => "Hides Hide the meta box from admin dashboard",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_recent_activity",
		"name" => "Hide Recent Comment",
		"description" => "Hides Recent comment form the dashboard",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_welcome_panel",
		"name" => "Hide Welcome Panel",
		"description" => "Hides the welcome panel",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);		
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_remove_custom_field",
		"name" => "Remove the custom Field ",
		"description" => "Remove the custom Field form page",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);		
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_remove_comment_status",
		"name" => "Remove Comment Status",
		"description" => "Remove the comment status from page",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);	
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_remove_comment_pages",
		"name" => "Remove Comment Pages",
		"description" => "Remove comments form pages",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);
	$fxdOptionsPermission[] = array(
		"id" => $fxd_label."_remove_author_pages",
		"name" => "Remove Author Option",
		"description" => "Remove author for page",
		"type" => "radio",
		"class"=> "radio",
		"option_value" => array("1","0"),
		"option_text" => array("YES" , "NO"),
		"std" => 0);				
$fxdOptionsPermission = array_merge($fxdOptionsPermission);
$fxd_show_appearance_legacy = '0';
$fxd_show_menus_legacy = '1';
$fxd_show_widgets_legacy = '1';
$fxdOptionsMenu[]='';
$fxdOptionsMenu = array_merge($fxdOptionsMenu);
?>